#include "help.h"

void print_help(){
       printf("Help about the program!\n");

       printf("This program has flags:\n"
              " -h, --help Prints the information help.\n"
              "    --info <file.bmp> Prints information about the bmp file.\n\n"
              "    --rect  [options]\n"
              "        -l --left_up <x.y> Sets the coordinates of the left point.\n"
              "        -r --right_down <x.y> Sets the coordinates of the lower right point.\n"
              "        -t --thickness <num>                                    Sets the line thickness.\n"
              " -with --color <rrr.ggg.bbb> Sets the line color.\n"
              " -f --fill Sets whether a fill is needed.\n"
              " -F --fill_color <rrr.ggg.bbb> Sets the fill colors.\n\n"
              "        -o --output <file.bmp> Sets the name of the output file.\n"
              "        -i --input <file.bmp> Sets the name of the input file.\n"
              "    --ornament [options] \n"
              "        -p --pattern [rectangle, circle, cemicircles]            Sets the ornament mode.\n"
              "        -t --thickness <num>                                    Sets the width of the line.\n"
              " -c --color <rrr.ggg.bbb> Sets the line color.\n"
              "        -C --count <num>                                        Sets the quantity.\n"
              "        -o --output <file.bmp> Sets the name of the output file.\n"
              "        -i --input <file.bmp> Sets the name of the input file.\n"
              "    --rotate [options] \n"
              "        -l --left_up <x.y> Sets the coordinates of the left point.\n"
              "        -r --right_down <x.y> Sets the coordinates of the lower right point.\n"
              "        -a --angle <num>                                        Sets the angle, maybe 90, 180, 270\n"
              " -o --output <file.bmp> Sets the name of the output file.\n"
              "        -i --input <file.bmp> Sets the name of the input file.\n"
              "    --circle [options]\n"
              "        -n --center <x.y> Sets the center of the circle.\n"
              "        -R --radius <num>                                       Sets the radius of the circle.\n"
              "        -t --thickness <num>                                    Sets the line thickness.\n"
              " -c --color <rrr.ggg.bbb> Sets the line color.\n"
              " -f --fill Sets whether a fill is needed.\n"
              " -F --fill_color <rrr.ggg.bbb> Sets the fill colors.\n\n"
              "        -o --output <file.bmp> Sets the name of the output file.\n"
              "        -i --input <file.bmp> Sets the name of the input file.\n");
}